"""TensorSmith: a compact tensor and neural-network framework."""

from . import amp, autograd, cuda, data, distributed, nn, optim
from .device import Device, available_devices, device, evaluate, is_available, seed, synchronize
from .serialization import load, save
from .tensor import (
    Tensor,
    arange,
    cat,
    empty,
    enable_grad,
    grad,
    is_grad_enabled,
    maximum,
    minimum,
    no_grad,
    ones,
    ones_like,
    rand,
    randn,
    stack,
    tensor,
    where,
    zeros,
    zeros_like,
)

__version__ = "0.3.0"

__all__ = [
    "Device",
    "Tensor",
    "amp",
    "arange",
    "autograd",
    "available_devices",
    "cat",
    "cuda",
    "data",
    "device",
    "distributed",
    "empty",
    "enable_grad",
    "evaluate",
    "grad",
    "is_available",
    "is_grad_enabled",
    "load",
    "maximum",
    "minimum",
    "nn",
    "no_grad",
    "ones",
    "ones_like",
    "optim",
    "rand",
    "randn",
    "save",
    "seed",
    "stack",
    "synchronize",
    "tensor",
    "where",
    "zeros",
    "zeros_like",
]
