"""Custom ML Library: explicit automatic differentiation."""

from .device import Device, available_devices, device, evaluate, is_available, seed, synchronize
from .tensor import (
    Tensor,
    arange,
    cat,
    empty,
    enable_grad,
    grad,
    is_grad_enabled,
    maximum,
    minimum,
    no_grad,
    ones,
    ones_like,
    rand,
    randn,
    stack,
    tensor,
    where,
    zeros,
    zeros_like,
)

__version__ = "0.1.0"
__all__ = [
    "Tensor",
    "arange",
    "cat",
    "empty",
    "enable_grad",
    "grad",
    "is_grad_enabled",
    "maximum",
    "minimum",
    "no_grad",
    "ones",
    "ones_like",
    "rand",
    "randn",
    "stack",
    "tensor",
    "where",
    "zeros",
    "zeros_like",
    "Device",
    "available_devices",
    "device",
    "evaluate",
    "is_available",
    "seed",
    "synchronize",
]
